trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing dependencies...
    npm install
    echo Packaging VSCode extension...
    npm install -g vsce
    vsce package
    echo Running tests...
    npm run test
  displayName: 'Build and Test'
